<a href="https://colab.research.google.com/github/Bipin-Gouda/DeepLearning/blob/main/Pytorch_YT_Crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [4]:
# torch.empty(size)
# torch.tensor()

x=torch.empty(3)
print(x)
y=torch.tensor([3,4])
print(y)

tensor([1.0138e-34, 0.0000e+00, 9.4383e-35])
tensor([3, 4])


In [6]:
print(x.dtype)
print(x.ndim,x.size())

torch.float32
1 torch.Size([3])


In [11]:
a=torch.rand(3,4,)
print(a)
b=torch.zeros(a.size())#size
print(b)
c=torch.ones(2,2)
print(c)

# Operations = +,-,/,*,@ (matmul) same rules of matrix

tensor([[0.1938, 0.1119, 0.3249, 0.3321],
        [0.3706, 0.6522, 0.3009, 0.1070],
        [0.9702, 0.3851, 0.2938, 0.6090]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
