<a href="https://colab.research.google.com/github/Bipin-Gouda/DeepLearning/blob/main/PyTorchYT1_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


# Tensor

In [ ]:
# defining a tensor normally
x=torch.tensor([3,4])
print(x,x.dtype,"dimensions=",x.ndim)

tensor([3, 4]) torch.int64 dimensions= 1


In [ ]:
x=torch.tensor(3.0)

In [ ]:
# Creating random tensors of  some input size torch.empty() oR torch.rand()
x=torch.empty(3,4)     # 1D,2D,3D,4D     
print(x,x.dtype)

tensor([[ 1.4599e-27,  4.5622e-41,  8.9258e-28,  4.5622e-41],
        [ 1.2943e-27,  4.5622e-41, -1.3920e+35,  4.5621e-41],
        [ 1.4876e-27,  4.5622e-41, -1.3920e+35,  4.5621e-41]]) torch.float32


In [ ]:
x=torch.rand(3,4,dtype=torch.double)
print(x.dtype)

torch.float64


In [ ]:
print(x)

tensor([[0.2012, 0.8797, 0.8704, 0.4898],
        [0.9017, 0.5701, 0.9588, 0.2072],
        [0.9882, 0.8264, 0.6434, 0.2933]], dtype=torch.float64)


# Ones & Zeros

In [ ]:
y=torch.ones(3,4,dtype=int)
print(y,y.size(),torch.dtype)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]) torch.Size([3, 4]) <class 'torch.dtype'>


In [ ]:
z= torch.zeros(3,4,dtype=torch.int64)

In [ ]:
print(z)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


# Range of tensors

In [ ]:
m=torch.arange(4,50,6)

In [ ]:
print(m,m.dtype,m.shape)

tensor([ 4, 10, 16, 22, 28, 34, 40, 46]) torch.int64 torch.Size([8])


# Operations

In [ ]:
x=torch.tensor([[1,2],
                [3,4]])
y=torch.tensor([[4,5],
                [6,7]])
print(x)
print(y)


tensor([[1, 2],
        [3, 4]])
tensor([[4, 5],
        [6, 7]])


In [ ]:
z=x+y    # oR torch.add(x,y)
print(z)

tensor([[ 5,  7],
        [ 9, 11]])


In [ ]:
z=x-y     # oR torch.sub(x,y)
print(z)

tensor([[-3, -3],
        [-3, -3]])


In [ ]:
z=x*y    # element wise - oR torch.mul(x,y)
print(z)

tensor([[ 4, 10],
        [18, 28]])


In [ ]:
z=x/y    # oR torch.div(x,y)
print(z)

tensor([[0.2500, 0.4000],
        [0.5000, 0.5714]])


In [ ]:
z=torch.matmul(x,y)  # matrix multiplication - matmul(), mm(), @
print(z)

tensor([[16, 19],
        [36, 43]])


# Inplace Operations

- all functions with `_`(underscore are inplace operations ie they willl change the original value

In [ ]:
print(x)
print(y)


tensor([[1, 2],
        [3, 4]])
tensor([[4, 5],
        [6, 7]])


In [ ]:
y.add_(x)
print(y)

tensor([[ 5,  7],
        [ 9, 11]])


In [ ]:
y.sub_(x)
print(y)

tensor([[4, 5],
        [6, 7]])


In [ ]:
y.mul_(x)
print(y)

tensor([[ 4, 10],
        [18, 28]])


In [ ]:
y=y.float()
print(y.dtype)     # we need to change datatype of y from int to float to store the changes which are decimal values  
y.div_(x)
y=y.int()
print(y)

torch.float32
tensor([[4, 5],
        [6, 7]], dtype=torch.int32)


# Slicing (indexing) like python

In [ ]:
x=torch.rand(5,3)
print(x)

tensor([[0.3082, 0.5841, 0.4121],
        [0.3906, 0.9803, 0.3291],
        [0.1537, 0.4788, 0.4847],
        [0.8678, 0.1334, 0.1896],
        [0.4418, 0.5333, 0.3697]])


In [ ]:
print(x[:,0]) # 1st column

tensor([0.3082, 0.3906, 0.1537, 0.8678, 0.4418])


In [ ]:
print(x[0,:])  # 1st row

tensor([0.3082, 0.5841, 0.4121])


In [ ]:
print(x[0,0]) # 1st element
print(x[1,1])
print(x[1,1].item()) # gives the actual value of a tensor NOte : Only applicable for single values

tensor(0.3082)
tensor(0.9803)
0.9803157448768616


# Reshaping tensors

- `view()` or `reshape()`
- Note: the number of elements must be same



In [ ]:
x= torch.rand(4,4)
print(x)
y=x.view(16)     
print(y)

tensor([[0.2049, 0.7562, 0.6128, 0.8899],
        [0.6321, 0.8004, 0.6921, 0.9288],
        [0.9541, 0.7081, 0.6510, 0.9426],
        [0.1168, 0.0910, 0.8431, 0.8225]])
tensor([0.2049, 0.7562, 0.6128, 0.8899, 0.6321, 0.8004, 0.6921, 0.9288, 0.9541,
        0.7081, 0.6510, 0.9426, 0.1168, 0.0910, 0.8431, 0.8225])


In [ ]:
y=x.reshape(16)  # or (1,16)  samething 
print(y)

tensor([0.2049, 0.7562, 0.6128, 0.8899, 0.6321, 0.8004, 0.6921, 0.9288, 0.9541,
        0.7081, 0.6510, 0.9426, 0.1168, 0.0910, 0.8431, 0.8225])


In [ ]:
# if we know only one dimension not the other we can use -1
print(x.view(-1,8))           #  2x8
print(x.reshape(8,-1))        #  8x2

tensor([[0.2049, 0.7562, 0.6128, 0.8899, 0.6321, 0.8004, 0.6921, 0.9288],
        [0.9541, 0.7081, 0.6510, 0.9426, 0.1168, 0.0910, 0.8431, 0.8225]])
tensor([[0.2049, 0.7562],
        [0.6128, 0.8899],
        [0.6321, 0.8004],
        [0.6921, 0.9288],
        [0.9541, 0.7081],
        [0.6510, 0.9426],
        [0.1168, 0.0910],
        [0.8431, 0.8225]])


# Numpy to torch tensor and vice versa


In [ ]:
import numpy as np

In [ ]:
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# tensor to numpy

b=a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


Note : they will both point to the same location if they are both in device 'cpu' sso cahnging one will change other too, eg-

In [ ]:
a.add_(1)
print(a)
print(b)      # both got added with 1

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
# numpy to tensor

a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
a+=1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#print(a.device)    # error as a is a numpy array
print(b.device)       # i

cpu


-  Note only cpu tensors are convertible to numpy array and vice versa for GPU tensors to cnvrt it to numpy array we need to cnvrt it to cpu tensor first.

In [ ]:
%%time
if torch.cuda.is_available():         # if we have GPU
  device=torch.device("cuda")         
  x=torch.ones(5, device=device)          # gpu tensor for faster operation
  # oR
  y=torch.ones(5)
  y=y.to(device)
  z=x@y
  print(z)
  #z.numpy()   
         


CPU times: user 415 µs, sys: 0 ns, total: 415 µs
Wall time: 2.23 ms


`requires_grad=True` by default it is False it tells pytorch it will have to calculate gradients for this tensor ie optimise it when required.


In [ ]:
x=torch.ones(5,requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
